version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql-db-002
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meetme
    ports:
      - "3308:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d